# Change these first
owner: KodeHomeCom # Your GitHub username
repo: kloudbucketstatus # The name of this repository

sites:
  - name: KloudBucket Main
    url: https://kloudbucket.com
  - name: KloudBucket Blog
    url: https://kloudbucket.com/blog
  - name: KloudBucket Contact
    url: https://kloudbucket.com/contact
  - name: User Dashboard
    url: https://kloudbucket.com/user/dashboard

status-website:
  # Your custom domain
  cname: status.kloudbucket.com
  # Logo and Favicon
  logoUrl: https://raw.githubusercontent.com/KodeHomeCom/kloudbucketstatus/refs/heads/master/assets/KloudBucket%20400x60.png
  faviconUrl: https://raw.githubusercontent.com/KodeHomeCom/kloudbucketstatus/refs/heads/master/assets/Favicon.png
  name: KloudBucket Status
  introTitle: "**KloudBucket** Real-Time Service Monitor"
  introMessage: This page monitors the uptime and performance of KloudBucket services. Powered by KodeHome Uptime Service.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://kloudbucket.com
    - title: GitHub
      href: https://github.com/KodeHomeCom/kloudbucketstatus

# Combined Automated settings (One single i18n section)
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: "KloudBucket is running perfectly."
  incidentReport: Incident Report
  footer: "© 2026 KloudBucket. All systems monitored by KodeHome Uptime Service."
