# Change these first
owner: KodeHomeCom # Your GitHub username
repo: kloudbucketstatus # The name of this repository

# Sites to monitor
sites:
  - name: KloudBucket Main
    url: https://kloudbucket.com
  - name: KloudBucket Blog
    url: https://kloudbucket.com/blog
  - name: KloudBucket Contact
    url: https://kloudbucket.com/contact
  - name: User Dashboard
    url: https://kloudbucket.com/user/dashboard

status-website:
  cname: status.kloudbucket.com
  
  # --- LOGO & FAVICON ---
  logoUrl: https://raw.githubusercontent.com/KodeHomeCom/kloudbucketstatus/master/assets/kloudbucket-logo.png
  faviconUrl: https://raw.githubusercontent.com/KodeHomeCom/kloudbucketstatus/master/assets/kb-favicon.svg
  
  name: Status
  introTitle: "**KloudBucket** Real-Time Service Monitor"
  introMessage: This page monitors the uptime and performance of KloudBucket services. Powered by KodeHome Uptime Service.
  
  # --- BRANDING & LOGO SIZE CONTROL ---
  customCSS: |
    /* Force Logo Height */
    .navbar-brand img, 
    header img { 
      height: 35px !important; 
      width: auto !important; 
    }
    /* Hide Upptime Branding Footer */
    footer p:nth-child(2) { display: none !important; }
    .footer a { color: #1da1f2 !important; }
  
  # Navbar must be at the same indentation level as customCSS and cname
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://kloudbucket.com

# Combined Automated settings
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: "KloudBucket is running perfectly."
  incidentReport: Incident Report
  footer: "© 2026 KloudBucket. All systems monitored by KodeHome Uptime Service."
